Makefile
coq/kleene.v

Prove the [Kleene fixed-point theorem](https://en.wikipedia.org/wiki/Kleene_fixed-point_theorem). The theorem states that the least fixed-point of a Scott-continuous function over a pointed directed-complete partial order exists and is the supremum of the ascending Kleene chain.

Prove the Kleene fixed-point theorem

---

coq/stlc.v

Switch the order of the typing rules and operational semantics in the STLC development. This is to match my [blog post](https://www.stephanboyer.com/post/134/my-unusual-hobby).

Switch the order of the typing rules and operational semantics in the STLC development

---

.gitignore

Make the .gitignore list more robust.

Make the .gitignore list more robust

---

Makefile

Fix the COQPATHs in the Makefile.

Fix the COQPATHs in the Makefile

---

Makefile

Fix the path to the Dockerfile.

Fix the path to the Dockerfile

---

scripts/Dockerfile

Add a stylistic line break to the Dockerfile.

Add a stylistic line break to the Dockerfile

---

coq/CategoryTheory.v

Formalize some category theory.

Formalize some category theory

---

coq/CategoryTheory.v

Formalize some operations on functors and natural transformations. Also, I fixed a couple of problems with the `Category` definition.

Formalize some operations on functors and natural transformations

---

coq/CategoryTheory.v

Rename some things and add an example to the category theory formalization.

Rename some things and add an example to the category theory formalization

---

coq/CategoryTheory.v

Formalize whiskering

---

coq/CategoryTheory.v

Formalize the definition of monad.

Formalize the definition of monad

---

coq/CategoryTheory.v

Prove that `Maybe` is a functor and a monad.

Prove that Maybe is a functor and a monad

---

coq/Intro.v
coq/Reflection.v

Simplify the 'evenness' example.

Simplify the 'evenness' example

---

coq/Kleene.v

Put the Kleene development in a module.

Put the Kleene development in a module

---

coq/CategoryTheory/MaybeMonad.v

Clarify some comments

---

Makefile

Remove a debugging line from the Makefile.

Remove a debugging line from the Makefile

---

coq/Intro.v

Add more intro content

---

coq/CategoryTheory/Maybe.v

Don't use any auto-named variables.

Don't use any auto-named variables

---

coq/CategoryTheory/Cat.v
coq/Tactics.v

Prove that categories form a category. Note that this development depends on functional extensionality and proof irrelevance, and I believe this is unavoidable.

Prove that categories form a category

---

coq/CategoryTheory/Cat.v
coq/CategoryTheory/Maybe.v
coq/CategoryTheory/NaturalTransformation.v
coq/Tactics.v

Simplify a few proofs

---

coq/CategoryTheory/Cat.v
coq/CategoryTheory/NaturalTransformation.v
coq/Tactics.v

Simplify some proofs

---

coq/CategoryTheory/Cat.v

Simplify the Cat proof

---

coq/CategoryTheory/Maybe.v

Simplify some more proofs

---

Makefile
scripts/Dockerfile

Create a user for the Docker image rather than doing the build as root.

Create a user for the Docker image rather than doing the build as root

---

Makefile

Indent a line in the Makefile.

Indent a line in the Makefile

---

coq/CategoryTheory/Category.v

Define the opposite category

---

coq/CategoryTheory/Cat.v
coq/CategoryTheory/Category.v
coq/CategoryTheory/Diagram.v
coq/CategoryTheory/Functor.v
coq/CategoryTheory/Monad.v
coq/CategoryTheory/NaturalTransformation.v
coq/CategoryTheory/Set.v
coq/Tactics.v

Formalize thin categories, diagrams, commutative diagrams, natural isomorphisms, and some properties about morphisms.

Formalize thin categories, diagrams, commutative diagrams, natural isomorphisms, and some properties about morphisms

---

coq/CategoryTheory/Category.v
coq/CategoryTheory/Functor.v
coq/CategoryTheory/NaturalTransformation.v

Remove some unnecessary resolve hints.

Remove some unnecessary resolve hints

---

coq/CategoryTheory/Cat.v
coq/Tactics.v

Remove unnecessary branching in the magic tactic.

Remove unnecessary branching in the magic tactic

---

coq/CategoryTheory/Category.v

Formalize initial and terminal objects.

Formalize initial and terminal objects

---

coq/CategoryTheory/Category.v
coq/CategoryTheory/Functor.v
coq/CategoryTheory/Monad.v
coq/CategoryTheory/NaturalTransformation.v
coq/Tactics.v

Prove facts about initial and terminal objects.

Prove facts about initial and terminal objects

---

coq/CategoryTheory/Category.v
coq/CategoryTheory/Maybe.v
coq/CategoryTheory/NaturalTransformation.v

Remove an unnecessary rewrite hint.

Remove an unnecessary rewrite hint

---

coq/CategoryTheory/Monad.v

Remove another unnecessary rewrite hint.

Remove another unnecessary rewrite hint

---

coq/Stlc/Preservation.v
coq/Stlc/Progress.v
coq/Stlc/Semantics.v
coq/Stlc/Syntax.v
coq/Stlc/Typing.v

Add Booleans to the STLC development.

Add Booleans to the STLC development

---

Makefile
scripts/Dockerfile

Adjust some formatting

---

scripts/Dockerfile

Pin the version of every package in the Docker image.

Pin the version of every package

---

coq/Intro.v

Fix some indentation to be consistent with the rest of the repo.
cc @jgonera

Fix some indentation

---

coq/Intro.v

Remove some unnecessary parentheses and also remove the eq definition.

Remove some unnecessary parentheses and also remove the eq definition

---

scripts/Dockerfile

Remove an extra space from the Dockerfile.

Remove an extra space from the Dockerfile

---

coq/Stlc/Semantics.v
coq/Stlc/Syntax.v
coq/Stlc/Typing.v

Alphabetize universal quantifications.

Alphabetize universal quantifications

---

coq/Kleene.v
coq/Stlc/Preservation.v
coq/Stlc/Progress.v
coq/Stlc/Soundness.v
coq/Stlc/Typing.v
coq/Tactics.v

Introduce a new `invert` tactic and other improvements.

Introduce a new 'invert' tactic and other improvements

---

coq/STLC/Progress.v

Make a slight improvement to the STLC progress proof.

Make a slight improvement to the STLC progress proof

---

coq/STLC/Soundness.v

Add the soundness theorem as a hint.

Add the soundness theorem as a hint

---

coq/STLC/Preservation.v

Make the STLC preservation proof a little more straightforward.

Make the STLC preservation proof a little more straightforward

---

coq/STLC/Preservation.v

Make a minor style improvement.

Make a minor style improvement

---

coq/STLC/Name.v
coq/STLC/Preservation.v
coq/STLC/Syntax.v
coq/STLC/Typing.v

Implement the `Name` signature (and rename it to `NameSig`).

Implement the 'Name' signature (and rename it to 'NameSig')

---

scripts/general-lint.sh

Lint for tabs

---

scripts/general-lint.sh

Fix a small typo

---

scripts/general-lint.sh

Fix another typo

---

.gitignore
Makefile

Update `make clean` to clean up Coq 8.7 files.

Update 'make clean' to clean up Coq 8.7 files

---

coq/STLC/FreeVars.v
coq/STLC/Preservation.v
coq/STLC/Progress.v
coq/STLC/Semantics.v
coq/STLC/Substitution.v

Refactor the STLC proofs

---

coq/Kleene.v
coq/STLC/Preservation.v
coq/STLC/Soundness.v
coq/Tactics.v

Make the `feed` tactic more magical.

Make the 'feed' tactic more magical

---

coq/Tactics.v

Update a comment

---

coq/Unambiguous.v

Prove that a simple grammar is unambiguous.

Prove that a simple grammar is unambiguous

---

coq/Tactics.v

Fix a small bug in the invert tactic.

Fix a small bug in the invert tactic

---

coq/STLC/Name.v

Add a hint

---

coq/Tactics.v

Add a stylistic line break

---

coq/CategoryTheory/Cat.v
coq/Kleene.v
coq/STLC/Name.v
coq/STLC/Preservation.v
coq/STLC/Progress.v
coq/STLC/Soundness.v
coq/Tactics.v

Improve the magic tactic

---

coq/Kleene.v
coq/Reflection.v
coq/Tactics.v

Simplfiy some proofs

---

coq/Tactics.v

Reorganize a couple of tactics.

Reorganize a couple of tactics

---

coq/CategoryTheory/Category.v
coq/Kleene.v
coq/Reflection.v
coq/STLC/Preservation.v
coq/STLC/Progress.v
coq/STLC/Soundness.v
coq/Tactics.v

Add an 'e' variant of `magic` and sort hypotheses in `simplify`.

Add an 'e' variant of magic and sort hypotheses in simplify

---

coq/CategoryTheory/Category.v
coq/CategoryTheory/Maybe.v
coq/CategoryTheory/NaturalTransformation.v
coq/Kleene.v
coq/Reflection.v
coq/STLC/Preservation.v
coq/STLC/Progress.v
coq/STLC/Soundness.v
coq/Tactics.v

Introduce the 'clean' tactic

---

coq/STLC/Preservation.v
coq/STLC/Progress.v
coq/STLC/Soundness.v

Remove unused imports

---

coq/Tactics.v

Smith some words

---

coq/Tactics.v

Simplify the `simplify` tactic.

Simplify the 'simplify' tactic

---

coq/Tactics.v

Be less specific in a comment.

Be less specific in a comment

---

coq/Tactics.v

Make a few style fixes

---

coq/STLC/Preservation.v
coq/Tactics.v

Automatically destruct `if` conditions in `magic`.

Automatically destruct 'if' conditions in 'magic'

---

coq/STLC/Preservation.v
coq/Tactics.v

Destruct conditionals in hypotheses.

Destruct conditionals in hypotheses

---

coq/Tactics.v

Simplify the `magicWith` tactic.

Simplify the magicWith tactic

---

coq/Kleene.v
coq/Reflection.v
coq/STLC/Preservation.v
coq/Tactics.v

Introduce the `gen` tactic notation.

Introduce the 'gen' tactic notation

---

coq/Tactics.v

Ensure that `magicWith` can solve the goal if the provided tactic can.

Ensure that magicWith can solve the goal if the provided tactic can

---

coq/Kleene.v

Use a section instead of a signature for the Kleene development.

Use a section instead of a signature for the Kleene development

---

coq/Kleene.v

Make minor style improvements to the Kleene development.

Make minor style improvements to the Kleene development

---

README.md

Rename the repo

---

coq/Tactics.v

Add some stylistic spacing

---

Makefile
scripts/Dockerfile

Upgrade to Coq 8.7.2

---

scripts/Dockerfile

Remove the Coq source after building.

Remove the Coq source after building

---

Makefile
coq/CategoryTheory/Maybe.v
coq/CategoryTheory/Monad.v
coq/STLC/Semantics.v

Check for unused or unsorted imports.

Check for unused or unsorted imports

---

Makefile
scripts/lint-general.rb
scripts/lint-imports.rb

Rewrite the import linter in Ruby and make minor improvements to both linters.

Rewrite the import linter in Ruby and make minor improvements to both linters

---

scripts/lint-imports.rb

Move some require statements

---

scripts/lint-imports.rb

Fix a minor style issue

---

Makefile
coq/STLC/Semantics.v

Check both `Require` and `Import` declarations.

Check both 'Require' and 'Import' declarations

---

Makefile

Ensure that 'make clean' happens before the other targets.

Ensure that 'make clean' happens before the other targets

---

coq/STLC/Preservation.v

Reorder some lemmas

---

.gitignore

Remove an unused `.gitignore` path.

Remove an unused .gitignore path

---

coq/Intro.v

Remove a couple distracting type annotations.

Remove a couple distracting type annotations

---

coq/SystemF/Context.v
coq/SystemF/FreeVar.v
coq/SystemF/LocalClosure.v
coq/SystemF/Name.v
coq/SystemF/Opening.v
coq/SystemF/OpeningSubstitution.v
coq/SystemF/Preservation.v
coq/SystemF/Progress.v
coq/SystemF/Semantics.v
coq/SystemF/Soundness.v
coq/SystemF/Substitution.v
coq/SystemF/Syntax.v
coq/SystemF/Typing.v

Formalize System F and prove the soundness theorem.

Formalize System F and prove the soundness theorem

---

README.md

Add instructions to the README.

Add instructions to the README

---

coq/STLC/FreeVar.v
coq/STLC/Preservation.v
coq/Tactics.v

Use a more economical definition for free variables in the STLC.

Use a more economical definition for free variables in the STLC

---

coq/STLC/FreeVar.v
coq/STLC/Preservation.v

Use a more consistent definition of free variables for the STLC.

Use a more consistent definition of free variables for the STLC

---

coq/Tactics.v

Fix some naming to improve consistency.

Fix some naming to improve consistency

---

Makefile
scripts/Dockerfile

Upgrade to Coq 8.0.0

---

.gitignore
Makefile

Fix the Makefile

---

coq/Tactics.v

Deduplicate some logic in the tactics.

Deduplicate some logic in the tactics

---

README.md

Remove some details from the README.

Remove some details from the README

---

coq/Intro/Lesson0_Intro.v
coq/Intro/Lesson1_DependentTypes.v
coq/Intro/Lesson2_Logic.v
coq/Intro/Lesson3_Induction.v

Make some formatting more consistent.

Make some formatting more consistent

---

coq/Intro/Lesson1_DependentTypes.v
coq/Intro/Lesson2_Logic.v

Fix some punctuation

---

coq/Intro/Lesson0_Intro.v
coq/Intro/Lesson1_DependentTypes.v
coq/Intro/Lesson2_Logic.v

Add a section about existential quantification in the tutorial.

Add a section about existential quantification in the tutorial

---

coq/Intro/Lesson2_Logic.v

Use the `Theorem` keyword for a theorem.

Use the 'Theorem' keyword for a theorem

---

Makefile
scripts/Dockerfile

Upgrade Coq to 8.8.2

---

coq/CategoryTheory/Product.v

Prove that categorical products are unique up to isomorphism.

Prove that categorical products are unique up to isomorphism

---

coq/CategoryTheory/Examples/CartesianProduct.v
coq/CategoryTheory/Product.v

Prove that cartesian products are categorical products in **SET**.

Prove that cartesian products are categorical products in SET

---

coq/CategoryTheory/Arrow.v

Prove that two-sided inverses are unique.

Prove that two-sided inverses are unique

---

coq/CategoryTheory/Arrow.v

Add a hint for the inverse uniqueness theorem.

Add a hint for the inverse uniqueness theorem

---

coq/Tactics.v

Make a comment more accurate according to the terminology in the [https://coq.inria.fr/refman/language/cic.html](Calculus of Inductive Constructions) section of the Coq documentation.

Make a comment more accurate

---

coq/CategoryTheory/Examples/Set.v

Remove an unnecessary qualification.

Remove an unnecessary qualification

---

coq/CategoryTheory/Arrow.v
coq/CategoryTheory/Coproduct.v
coq/CategoryTheory/Examples/Set.v
coq/CategoryTheory/Object.v
coq/CategoryTheory/Product.v

Rename and remove some things in the category theory formalization.

Rename and remove some things in the category theory formalization

---

coq/CategoryTheory/NaturalTransformation.v

Slightly simplify a proof about natural transformations.

Slightly simplify a proof about natural transformations

---

coq/CategoryTheory/Arrow.v
coq/CategoryTheory/Coproduct.v
coq/CategoryTheory/Object.v

Formalize retractions and sections, prove basic results about them, and refactor some other proofs.

Formalize retractions and sections, prove basic results about them, and refactor some other proofs

---

coq/CategoryTheory/Coproduct.v
coq/CategoryTheory/Object.v

Prove that `isomorphic` is an equivalence relation.

Prove that `isomorphic` is an equivalence relation

---

coq/CategoryTheory/Arrow.v

Prove that inverse is an involution.

Prove that inverse is an involution

---

coq/CategoryTheory/Arrow.v
coq/CategoryTheory/Object.v
coq/CategoryTheory/Product.v

Define `isomorphism` in terms of `inverse`.

Define `isomorphism` in terms of `inverse`

---

coq/CategoryTheory/Arrow.v
coq/CategoryTheory/Coproduct.v
coq/CategoryTheory/Initial.v
coq/CategoryTheory/Object.v
coq/CategoryTheory/Product.v
coq/CategoryTheory/Terminal.v

Prove the commutativity property for products and coproducts.

 Prove the commutativity property for products and coproducts

---

coq/Intro/Lesson0_Intro.v
coq/Intro/Lesson1_DependentTypes.v
coq/Intro/Lesson2_Logic.v
coq/Intro/Lesson3_Induction.v
coq/Metatheory.v

Add a new file demonstrating some of Coq's metatheory.

Add a new file demonstrating some of Coq's metatheory

---

coq/CategoryTheory/Coproduct.v
coq/CategoryTheory/Product.v

Prove that products and coproducts are associative up to isomorphism.
I have to say, this was the one of the most unenlightening, strenuous, and obnoxiously mechanical proofs I've ever done.

Prove that products and coproducts are associative up to isomorphism

---

coq/CategoryTheory/Object.v
coq/CategoryTheory/Product.v

Simplify a couple proofs

---

coq/Intro/Lesson3_Induction.v
coq/Intro/Lesson4_Extraction.v

Add an example of extraction to Haskell.

Add an example of extraction to Haskell

---

coq/Intro/Lesson2_Logic.v

Make some arguments implicit

---

coq/CategoryTheory/Examples/Cat.v
coq/CategoryTheory/Examples/Maybe.v
coq/CategoryTheory/Examples/Set.v
coq/CategoryTheory/Functor.v

Refactor some of the category theory development.

Refactor some of the category theory development

---

coq/CategoryTheory/Equivalence.v

Formalize the notion of equivalence of categories.

Formalize the notion of equivalence of categories

---

coq/CategoryTheory/Arrow.v
coq/CategoryTheory/Equivalence.v

Prove that equivalence of categories is reflexive.

Prove that equivalence of categories is reflexive

---

coq/CategoryTheory/Examples/Maybe.v
coq/CategoryTheory/Monad.v
coq/CategoryTheory/NaturalTransformation.v

Formalize horizontal composition of natural transformations.

Formalize horizontal composition of natural transformations

---

coq/CategoryTheory/Monad.v

Prove a monad equality theorem.

Prove a monad equality theorem

---

coq/CategoryTheory/README.md

Do some minor wordsmithing on a README.

Do some minor wordsmithing

---

coq/STLC/README.md

Fix a broken URL

---

toast.yml

Export intermediate build artifacts to support incremental compilation.

Export intermediate build artifacts to support incremental compilation

---

toast.yml

Upgrade Coq to version 8.10.1.

Upgrade Coq to version 8.10.1

---

toast.yml

Upgrade Coq to version 8.10.2.

Upgrade Coq to version 8.10.2

---

proofs/Metatheory/Metatheory.v

Add an example demonstrating how inductive families are equivalent to propositional equality + inductive types.

Add an example demonstrating how inductive families are equivalent to propositional equality + inductive types

---

.gitignore
Makefile
README.md
proofs/CategoryTheory/Category.v
proofs/CategoryTheory/Examples/Maybe.v
proofs/CategoryTheory/Examples/Set.v
proofs/CategoryTheory/Functor.v
proofs/CategoryTheory/NaturalTransformation.v
proofs/CategoryTheory/ProductCategory.v
proofs/Kleene/Kleene.v
proofs/SystemF/LocalClosure.v
proofs/SystemF/Name.v
proofs/SystemF/Opening.v
toast.yml

Update Coq to v8.11.0

---

proofs/STLC/README.md
proofs/SystemF/README.md

Fix a couple of URLs

---

proofs/Intro/Lesson0_Intro.v

Wordsmith a comment. The type here is either `Boolean` (English) or `bool` (Coq), but not `Bool`.

Wordsmith a comment

---

toast.yml

Upgrade Coq to v8.13.0

---

README.md
proofs/STLC/README.md
proofs/SystemF/README.md

Rename the default branch

---

.github/workflows/ci.yml

Update the Toast branch name

---

toast.yml

Upgrade Coq to v8.15.0

---

toast.yml

Refactor the toastfile

---

scripts/lint-imports.rb

Use a consistent case convention in the Ruby scripts.

Use a consistent case convention in the Ruby scripts

---

proofs/Intro/Lesson2_Logic.v
proofs/Intro/Lesson4_Extraction.v

Fix a couple typos

---

proofs/CategoryTheory/Category.v
proofs/CategoryTheory/Examples/Maybe.v
proofs/CategoryTheory/Examples/Set.v
proofs/CategoryTheory/Functor.v
proofs/CategoryTheory/NaturalTransformation.v
proofs/CategoryTheory/ProductCategory.v
proofs/Kleene/Kleene.v
proofs/SystemF/Substitution.v

Migrate from using legacy attributes to new attributes.

Migrate from using legacy attributes to new attributes

---

_CoqProject
scripts/lint-imports.rb

Fix a typo in a linter script.

Fix a typo in a linter script

---

LICENSE.md
_CoqProject

Add a clarification in the LICENSE.

Add a clarification in the LICENSE

---

proofs/Tactics.v

Add the `local` attribute to some tactics.

Add the `local` attribute to some tactics

---

README.md
proofs/Tutorial/Lesson3_Induction.v

Use contractions where appropriate.

Use contractions where appropriate

---

proofs/Tutorial/Lesson2_Logic.v

Fix a typo in a comment

---

proofs/Tutorial/Lesson4_Reflection.v

Rework the reflection tutorial.

Rework the reflection tutorial

---

.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md
CODE_OF_CONDUCT.md

Add community standards

---

proofs/Tactics.v

Explicitly use specific hint databases.
**Fixes:** N/A

Explicitly use specific hint databases

---

linters/lint-general.rb

Improve the lint reporting.
**Fixes:** N/A

Improve the lint reporting

---

proofs/GirardParadox/GirardParadox.v
proofs/GirardParadox/README.md

Add a demonstration of Girard's paradox.
**Fixes:** N/A

Add a demonstration of Girard's paradox

---

proofs/ContextGraph/ContextGraph.v
proofs/ContextGraph/README.md

Introduce context graphs.
**Fixes:** N/A

Introduce context graphs

---

proofs/ContextGraph/README.md

Update the description of context graphs.
My intuition about context graphs is still developing. There are multiple ways to think about them, and some seem to be more useful than others.
**Fixes:** N/A

Update the description of context graphs

---

proofs/ContextGraph/ContextGraph.v

Rename `universe` to `origin`.
**Fixes:** N/A

Rename `universe` to `origin`

---

proofs/ContextGraph/ContextGraph.v

Introduce two notions of reachability for context graphs.
**Fixes:** N/A

Introduce two notions of reachability for context graphs

---

proofs/ContextGraph/ContextGraph.v

Require vertical reachability to be antisymmetric.
**Fixes:** N/A

Require vertical reachability to be antisymmetric

---

proofs/ContextGraph/ContextGraph.v

Do some wordsmithing on the context graph development.
**Fixes:** N/A

Do some wordsmithing on the context graph development

---

proofs/ContextGraph/ContextGraph.v

Refactor the context graph development.
**Fixes:** N/A

Refactor the context graph development

---

proofs/ContextGraph/ContextGraph.v
proofs/ContextGraph/TrivialContextGraph.v
proofs/Kleene/Kleene.v
proofs/Kleene/TrivialKleeneData.v
proofs/SystemF/Substitution.v
toast.yml

Use modules instead of sections.
**Fixes:** N/A

Use modules instead of sections

---

proofs/ContextGraph/Closure.v
proofs/ContextGraph/ContextGraph.v
proofs/ContextGraph/TrivialContextGraph.v

Simplify the context graph development.
**Fixes:** N/A

Simplify the context graph development

---

proofs/ContextGraph/ContextGraph.v

Remove a useless sentence from a comment.
**Fixes:** N/A

Remove a useless sentence from a comment

---

proofs/ContextGraph/ContextGraph.v

Introduce diagonal reachability.
**Fixes:** N/A

Introduce diagonal reachability

---

proofs/ContextGraph/ContextGraph.v
proofs/ContextGraph/TrivialContextGraph.v

Use shorter names for things.
**Fixes:** N/A

Use shorter names for things

---

proofs/Experiments/Overtree/Overtree.v

Simplify a proof.
**Fixes:** N/A

Simplify a proof

---

proofs/Experiments/ContextGraph/ContextGraph.v
proofs/Experiments/ContextGraph/TrivialContextGraph.v

Make the two graph developments more consistent with each other.
**Fixes:** N/A

Make the two graph developments more consistent with each other

---

README.md

Update the list of dependencies.
**Fixes:** N/A

Update the list of dependencies

---

proofs/Experiments/Overtree/Overtree.v

Do some minor refactoring.
**Fixes:** N/A

Do some minor refactoring

---

proofs/Experiments/Overtree/Overtree.v
proofs/Experiments/Overtree/TrivialOvertree.v

Introduce an axiom to the overtree development which gives it nicer properties.
**Fixes:** N/A

Introduce an axiom to the overtree development which gives it nicer properties

---

proofs/Experiments/ContextGraph/ContextGraph.v
proofs/Experiments/ContextGraph/TrivialContextGraph.v
proofs/Experiments/Overtree/Overtree.v
proofs/Experiments/Overtree/OvertreeTheorems.v
proofs/Experiments/Overtree/TrivialOvertree.v
proofs/Tactics.v

Improve the proof automation.
**Fixes:** N/A

Improve the proof automation

---

proofs/Kleene/KleeneData.v
proofs/Kleene/KleeneTheorems.v
proofs/Kleene/TrivialKleeneData.v

Move the Kleene modules into dedicated files.
**Fixes:** N/A

Move the Kleene modules into dedicated files

---

proofs/CategoryTheory/Product.v
proofs/Kleene/KleeneTheorems.v
proofs/SystemF/Typing.v

Always use bullets instead of `{ ... }`.
**Fixes:** N/A

Always use bullets instead of `{ ... }`

---

proofs/Experiments/ContextGraph/ContextGraph.v
proofs/Experiments/Overtree/Overtree.v
proofs/Experiments/Overtree/OvertreeTheorems.v
proofs/Experiments/Overtree/TrivialOvertree.v

Remove some generous line breaks.
**Fixes:** N/A

Remove some generous line breaks

---

proofs/TypeTheory/Church.v

Define a non-dependent second projection function for dependent Church pairs.
**Fixes:** N/A

Define a non-dependent second projection function for dependent Church pairs

---

proofs/TypeTheory/Church.v

Replace an abbreviation with the full word.
**Fixes:** N/A

Replace an abbreviation with the full word

---

proofs/TypeTheory/Church.v

Update the second projection for dependent pairs with non-dependent elimination.
**Fixes:** N/A

Update the second projection for dependent pairs with non-dependent elimination

---

proofs/TypeTheory/Church.v

Refactor the Church encodings.
**Fixes:** N/A

Refactor the Church encodings

---

proofs/TypeTheory/Church.v

Clarify some terminology related to pairs (strong/weak existentials, sigmas, etc.).
**Fixes:** N/A

Clarify some terminology related to pairs (strong/weak existentials, sigmas, etc.)

---

proofs/TypeTheory/Church.v

Rename a function.
**Fixes:** N/A

Rename a function

---

proofs/TypeTheory/Church.v

Use an impredicative universe for the Church encodings.
**Fixes:** N/A

Use an impredicative universe for the Church encodings

---

proofs/TypeTheory/Church.v

Prove the beta and eta equivalences (when possible) for the Church encodings.
**Fixes:** N/A

Prove the beta and eta equivalences (when possible) for the Church encodings

---

proofs/Experiments/ContextGraph/TrivialContextGraph.v
proofs/Experiments/Overtree/TrivialOvertree.v
proofs/Kleene/TrivialKleeneData.v
proofs/Tactics.v

Tweak the tactics.
**Fixes:** N/A

Tweak the tactics

---

proofs/TypeTheory/Indices.v

Flesh out the `Indices` module.
**Fixes:** N/A

Flesh out the `Indices` module

---

proofs/Experiments/Overtree/TrivialOvertree.v

Remove an unnecessary hint.
**Fixes:** N/A

Remove an unnecessary hint

---

proofs/Tutorial/Lesson5_Consistency.v

Expand the `Consistency` lesson in the tutorial.
**Fixes:** N/A

Expand the `Consistency` lesson in the tutorial

---

proofs/Tutorial/Lesson6_Extraction.v

Tweak a comment.
**Fixes:** N/A

Tweak a comment

---

proofs/Tutorial/Lesson5_Consistency.v

Add an example of a reflexive type to the tutorial.
**Fixes:** N/A

Add an example of a reflexive type to the tutorial

---

proofs/TypeTheory/Girard.v
proofs/TypeTheory/README.md

Update a README.
**Fixes:** N/A

Update a README

---

proofs/TypeTheory/Indices.v

Remove punctuation from a non-sentence.
**Fixes:** N/A

Remove punctuation from a non-sentence

---

proofs/TypeTheory/Indices.v

Reformat some ugly code.
**Fixes:** N/A

Reformat some ugly code

---

proofs/TypeTheory/Indices.v

Reformulate the `Indices` module.
**Fixes:** N/A

Reformulate the `Indices` module

---

proofs/TypeTheory/Indices.v

Add a couple of hints.
**Fixes:** N/A

Add a couple of hints

---

proofs/TypeTheory/Indices.v

Refactor the `Indices` module.
**Fixes:** N/A

Refactor the `Indices` module

---

proofs/TypeTheory/Church.v

Elaborate in a comment.
**Fixes:** N/A

Elaborate in a comment

---

proofs/TypeTheory/Church.v
proofs/TypeTheory/Girard.v

Tweak some comments.
**Fixes:** N/A

Tweak some comments

---

proofs/Tutorial/Lesson5_Consistency.v

Explain the universe constraints related to inductive types.
**Fixes:** N/A

Explain the universe constraints related to inductive types

---

proofs/Tutorial/Lesson5_Consistency.v

Make a comment more precise.
**Fixes:** N/A

Make a comment more precise

---

proofs/Tutorial/Lesson6_Extraction.v

Make a `Require` more robust.
**Fixes:** N/A

Make a `Require` more robust

---

proofs/Tutorial/Lesson0_Intro.v

Rewrite lesson 0 from the tutorial.
**Fixes:** N/A

Rewrite lesson 0 from the tutorial

---

proofs/Tutorial/Lesson0_Intro.v

Tweak lesson 0 from the tutorial.
**Fixes:** N/A

Tweak lesson 0 from the tutorial

---

proofs/Tutorial/Lesson0_Intro.v

Add some missing backticks in some comments.
**Fixes:** N/A

Add some missing backticks in some comments

---

proofs/Tutorial/Lesson0_Intro.v

Tweak lesson 0 of the tutorial.
**Fixes:** N/A

Tweak lesson 0 of the tutorial

---

proofs/Tutorial/Lesson0_Intro.v

Add a step to lesson 0 of the tutorial.
**Fixes:** N/A

Add a step to lesson 0 of the tutorial

---

proofs/Tutorial/Lesson0_Intro.v

Explain `forall` types in the tutorial.
**Fixes:** N/A

Explain `forall` types in the tutorial

---

proofs/Tutorial/Lesson1_Intro.v

Tweak lesson 1.
**Fixes:** N/A

Tweak lesson 1

---

proofs/Tutorial/Lesson5_Consistency.v

Rename some things in the tutorial.
**Fixes:** N/A

Rename some things in the tutorial

---

proofs/Tutorial/Lesson1_Intro.v

Add some exercises to the tutorial.
**Fixes:** N/A

Add some exercises to the tutorial

---

proofs/Tutorial/Lesson1_Intro.v
proofs/Tutorial/Lesson2_DependentTypes.v

Update Lesson 2 of the tutorial.
**Fixes:** N/A

Update Lesson 2 of the tutorial

---

proofs/Tutorial/Lesson2_DependentTypes.v

Put some more effort into Lesson 2.
**Fixes:** N/A

Put some more effort into Lesson 2

---

proofs/Tutorial/Lesson1_Intro.v

Wordsmith Lesson 1.
**Fixes:** N/A

Wordsmith Lesson 1

---

proofs/Tutorial/Lesson2_DependentTypes.v

Wordsmith Lesson 2.
**Fixes:** N/A

Wordsmith Lesson 2

---

proofs/Tutorial/Lesson2_DependentTypes.v

Add a `head` function to Lesson 2.
**Fixes:** N/A

Add a `head` function to Lesson 2

---

proofs/Tutorial/Lesson1_Intro.v

Explain the `@` syntax in Lesson 1.
**Fixes:** N/A

Explain the `@` syntax in Lesson 1

---

proofs/Tutorial/Lesson1_Intro.v

Generalize the type of `mapOption` in Lesson 1.
**Fixes:** N/A

Generalize the type of `mapOption` in Lesson 1

---

proofs/Tutorial/Lesson1_Intro.v

Add some exercises for Lesson 1 of the tutorial.
**Fixes:** N/A

Add some exercises for Lesson 1 of the tutorial

---

proofs/Tutorial/Lesson1_Intro.v

Add some `Check` commands in the tutorial.
**Fixes:** N/A

Add some `Check` commands in the tutorial

---

proofs/Tutorial/Lesson1_Intro.v
proofs/Tutorial/Lesson2_DependentTypes.v

Add exercises to Lesson 2 of the tutorial.
**Fixes:** N/A

Add exercises to Lesson 2 of the tutorial

---

proofs/Tutorial/Lesson2_DependentTypes.v

Refactor Lesson 2 of the tutorial.
**Fixes:** N/A

Refactor Lesson 2 of the tutorial

---

proofs/Tutorial/Lesson2_DependentTypes.v

Add a callout to Lesson 5.
**Fixes:** N/A

Add a callout to Lesson 5

---

proofs/Tutorial/Lesson2_DependentTypes.v

Change `Type` to `Set` in Lesson 2.
**Fixes:** N/A

Change `Type` to `Set` in Lesson 2

---

proofs/Tutorial/Lesson1_Intro.v
proofs/Tutorial/Lesson2_DependentTypes.v
proofs/Tutorial/Lesson5_Consistency.v
proofs/Tutorial/README.md

Clarify some comments in the tutorial.
**Fixes:** N/A

Clarify some comments in the tutorial

---

proofs/Tutorial/Lesson3_Logic.v

Fix a typo

---

proofs/TypeTheory/Indices.v

Add a clarifying comment about parameters and indices.
**Fixes:** N/A

Add a clarifying comment about parameters and indices

---

proofs/Tutorial/Lesson2_DependentTypes.v

Fix some typos in a comment.
**Fixes:** N/A

Fix some typos in a comment

---

proofs/Tutorial/Lesson3_Logic.v

Tweak the logic tutorial.
**Fixes:** N/A

Tweak the logic tutorial

---

proofs/Tutorial/Lesson1_Intro.v
proofs/Tutorial/Lesson3_Logic.v

Flesh out the logic tutorial.
**Fixes:** N/A

Flesh out the logic tutorial

---

proofs/Tutorial/Lesson3_Logic.v

Explain implication in the logic lesson.
**Fixes:** N/A

Explain implication in the logic lesson

---

proofs/Tutorial/Lesson3_Logic.v
proofs/Tutorial/Lesson4_Induction.v

Refactor the tutorial.
**Fixes:** N/A

Refactor the tutorial

---

proofs/Tutorial/Lesson2_DependentTypes.v
proofs/Tutorial/Lesson5_Consistency.v
proofs/Tutorial/Lesson6_Extraction.v

Make some parts of the tutorial easier to read with `Fail`.
**Fixes:** N/A

Make some parts of the tutorial easier to read with `Fail`

---

proofs/Tutorial/Lesson3_Logic.v

Use standard notations for the logic tutorial.
**Fixes:** N/A

Use standard notations for the logic tutorial

---

proofs/Tutorial/Lesson1_Intro.v
proofs/Tutorial/Lesson2_DependentTypes.v
proofs/Tutorial/Lesson3_Logic.v

Use `#[local]` instead of `Local`.
**Fixes:** N/A

Use `#[local]` instead of `Local`

---

proofs/Tutorial/Lesson3_Logic.v

Fix a few typos.
**Fixes:** N/A

Fix a few typos

---

proofs/Tutorial/Lesson3_Logic.v

Add more manual proofs to the tutorial.
**Fixes:** N/A

Add more manual proofs to the tutorial

---

proofs/Tutorial/Lesson3_Logic.v

Explain propositional equality in the tutorial.
**Fixes:** N/A

Explain propositional equality in the tutorial

---

proofs/Tutorial/Lesson1_Intro.v
proofs/Tutorial/Lesson2_DependentTypes.v
proofs/Tutorial/Lesson3_Logic.v
proofs/Tutorial/README.md

Add a note about using a Coq-aware IDE.
**Fixes:** N/A

Add a note about using a Coq-aware IDE

---

proofs/Tutorial/Lesson3_Logic.v

Add a couple proofs to the logic tutorial.
**Fixes:** N/A

Add a couple proofs to the logic tutorial

---

proofs/Tutorial/Lesson3_Logic.v

Use `Goal` instead of `Theorem` to avoid having to come up with multiple names for the same theorem.
**Fixes:** N/A

Use `Goal` instead of `Theorem` to avoid having to come up with multiple names for the same theorem

---

proofs/Tutorial/Lesson3_Logic.v

Rename a theorem for consistency.
**Fixes:** N/A

Rename a theorem for consistency

---

proofs/Tutorial/Lesson3_Logic.v

Add two proofs to the tutorial.
**Fixes:** N/A

Add two proofs to the tutorial

---

proofs/Tutorial/Lesson3_Logic.v

Use the notation for equality in `in` clauses.
**Fixes:** N/A

Use the notation for equality in `in` clauses

---

proofs/Tutorial/Lesson4_ProofTechniques.v

Rename one of the lessons in the tutorial.
**Fixes:** N/A

Rename one of the lessons in the tutorial

---

proofs/Tutorial/Lesson3_Logic.v
proofs/Tutorial/Lesson4_ProofTechniques.v

Update the "proof techniques" lesson of the tutorial.
**Fixes:** N/A

Update the "proof techniques" lesson of the tutorial

---

proofs/Tutorial/Lesson4_ProofTechniques.v

Add a note about large elimination.
**Fixes:** N/A

Add a note about large elimination

---

proofs/Tutorial/Lesson4_ProofTechniques.v

Add a section on `f_equal` to the tutorial.
**Fixes:** N/A

Add a section on `f_equal` to the tutorial

---

proofs/Tactics.v
proofs/Tutorial/Lesson4_ProofTechniques.v

Add a section on automation to the tutorial.
**Fixes:** N/A

Add a section on automation to the tutorial

---

proofs/Tutorial/Lesson4_ProofTechniques.v

Refactor the proof techniques lesson in the tutorial.
**Fixes:** N/A

Refactor the proof techniques lesson in the tutorial

---

proofs/Tutorial/Lesson6_Extraction.v

Update the extraction lesson in the tutorial.
**Fixes:** N/A

Update the extraction lesson in the tutorial

---

proofs/Tutorial/Lesson3_Logic.v
proofs/Tutorial/Lesson4_ProofTechniques.v
proofs/Tutorial/Lesson6_Extraction.v

Tweak the extraction tutorial.
**Fixes:** N/A

Tweak the extraction tutorial

---

proofs/Tutorial/Lesson6_Extraction.v

Demonstrate the `Program` command.
**Fixes:** N/A

Demonstrate the `Program` command

---

proofs/Tutorial/Lesson4_ProofTechniques.v
proofs/Tutorial/README.md

Update the README for the tutorial.
**Fixes:** N/A

Update the README for the tutorial

---

proofs/Tutorial/Lesson4_ProofTechniques.v
proofs/Tutorial/Lesson5_Consistency.v
proofs/Tutorial/Lesson6_Extraction.v

Add exercises for the last three lessons of the tutorial.
**Fixes:** N/A

Add exercises for the last three lessons of the tutorial

---

proofs/Tutorial/Lesson4_ProofTechniques.v

Tweak the proof techniques lesson of the tutorial.
**Fixes:** N/A

Tweak the proof techniques lesson of the tutorial

---

proofs/STLC/Preservation.v
proofs/SystemF/LocalClosure.v
proofs/SystemF/Opening.v
proofs/SystemF/OpeningSubstitution.v
proofs/SystemF/Preservation.v
proofs/SystemF/Substitution.v
proofs/SystemF/Typing.v
proofs/Tactics.v

Replace `gen` with `outro`.
**Fixes:** N/A

Replace `gen` with `outro`

---

proofs/Tutorial/Lesson4_ProofTechniques.v

Clarify that `assert` had not yet been introduced at a particular point in the tutorial.
**Fixes:** N/A

Clarify that `assert` had not yet been introduced at a particular point in the tutorial

---

proofs/Tutorial/Lesson1_Intro.v
proofs/Tutorial/Lesson2_DependentTypes.v
proofs/Tutorial/Lesson4_ProofTechniques.v

Do some wordsmithing.
**Fixes:** N/A

Do some wordsmithing

---

proofs/Tutorial/Lesson1_Intro.v

Do some wordsmithing on the tutorial.
**Fixes:** N/A

Do some wordsmithing on the tutorial

---

proofs/Tutorial/Lesson1_Intro.v
proofs/Tutorial/Lesson4_ProofTechniques.v

Fix some typos in comments.
**Fixes:** N/A

Fix some typos in comments

---

proofs/CategoryTheory/Coproduct.v
proofs/CategoryTheory/Initial.v
proofs/CategoryTheory/Product.v
proofs/Experiments/Overtree/OvertreeTheorems.v
proofs/Kleene/KleeneTheorems.v
proofs/STLC/Preservation.v
proofs/SystemF/Context.v
proofs/SystemF/Preservation.v
proofs/SystemF/Progress.v
proofs/SystemF/Semantics.v
proofs/SystemF/Substitution.v
proofs/SystemF/Typing.v
proofs/Tactics.v

Use `pose proof` instead of `fact`.
**Fixes:** N/A

Use `pose proof` instead of `fact`

---

proofs/Tutorial/Lesson3_Logic.v

Clarify that `apply conj` can be used to prove a conjunction.
**Fixes:** N/A

Clarify that `apply conj` can be used to prove a conjunction

---

proofs/Tutorial/Lesson1_Intro.v

Use `Fail` in the tutorial instead of putting invalid code in a comment.
**Fixes:** N/A

Use `Fail` in the tutorial instead of putting invalid code in a comment

---

proofs/Tutorial/Lesson5_Consistency.v

Clarify a comment about universes.
**Fixes:** N/A

Clarify a comment about universes

---

proofs/Tutorial/Lesson1_FunctionalProgramming.v

Clarify the comment explaining arrow types.
**Fixes:** N/A

Clarify the comment explaining arrow types

---

proofs/HomotopyTypeTheory/README.md
proofs/HomotopyTypeTheory/Univalence.v

Add a new homotopy type theory directory.
**Fixes:** N/A

Add a new homotopy type theory directory

---

proofs/TypeTheory/README.md

Wordsmith the type theory README.
**Fixes:** N/A

Wordsmith the type theory README

---

proofs/TypeTheory/Univalence.v

Simplify the definition of equivalence.
**Fixes:** N/A

Simplify the definition of equivalence

---

proofs/TypeTheory/Univalence.v

Change some types in the univalence formalization.
**Fixes:** N/A

Change some types in the univalence formalization

---

proofs/Tutorial/Lesson3_Logic.v

Simplify the proof that equality is transitive.
**Fixes:** N/A

Simplify the proof that equality is transitive

---

proofs/Tutorial/Lesson2_DependentTypes.v

Add a couple missing comments.
**Fixes:** N/A

Add a couple missing comments

---

proofs/Tutorial/Lesson2_DependentTypes.v

Make a comment less confusing.
**Fixes:** N/A

Make a comment less confusing

---

proofs/Tutorial/Lesson2_DependentTypes.v

Explain indices better.
**Fixes:** N/A

Explain indices better

---

_CoqProject
linters/lint-imports.rb
toast.yml

Update the compiler flags.
**Fixes:** N/A

Update the compiler flags

---

proofs/Tactics.v
proofs/Tutorial/Lesson4_ProofTechniques.v

Update the automation part of the tutorial.
**Fixes:** N/A

Update the automation part of the tutorial

---

proofs/Tutorial/Lesson4_ProofTechniques.v

Wordsmith some comments.
**Fixes:** N/A

Wordsmith some comments

---

proofs/Tutorial/Lesson4_ProofTechniques.v

Explain how to change the search depth for `auto`.
**Fixes:** N/A

Explain how to change the search depth for `auto`

---

proofs/Tutorial/Lesson5_Consistency.v

Simplify the explanation of how universes interact with inductive types.
**Fixes:** N/A

Simplify the explanation of how universes interact with inductive types

---

proofs/Tutorial/Lesson5_Consistency.v

Update the syntax in a comment to be more like Latex.
**Fixes:** N/A

Update the syntax in a comment to be more like Latex

---

proofs/Tutorial/Lesson4_ProofTechniques.v
proofs/Tutorial/Lesson5_Consistency.v

Update the tutorial chapter on proof techniques.
**Fixes:** N/A

Update the tutorial chapter on proof techniques

---

proofs/ICBICS/ICBICS.v
proofs/ICBICS/README.md

Add a proof of the correctness of the simplest and most surprising sorting algorithm ever.
**Fixes:** N/A

Add a proof of the correctness of the simplest and most surprising sorting algorithm ever

---

proofs/ICBICS/ICBICS.v

Fix the citation for the "I can't believe it can sort" algorithm.
**Fixes:** N/A

Fix the citation for the "I can't believe it can sort" algorithm

---

proofs/ICBICS/README.md

Use slightly different notation for the pseudocode.
**Fixes:** N/A

Use slightly different notation for the pseudocode

---

proofs/ICBICS/ICBICS.v

Delete an unused lemma.
**Fixes:** N/A

Delete an unused lemma

---

proofs/ICBICS/ICBICS.v

Remove some superfluous comments.
**Fixes:** N/A

Remove some superfluous comments

---

proofs/ICBICS/ICBICS.v

Add a comment describing the ICBICS algorithm.
**Fixes:** N/A

Add a comment describing the ICBICS algorithm

---

proofs/ICBICS/ICBICS.v

Refactor the ICBICS proof.
**Fixes:** N/A

Refactor the ICBICS proof

---

proofs/ICBICS/ICBICS.v

Remove an unused hypothesis.
**Fixes:** N/A

Remove an unused hypothesis

---

proofs/Experiments/ContextGraph/ContextGraphTheorems.v
proofs/Experiments/ContextGraph/TrivialContextGraph.v
proofs/Experiments/Overtree/OvertreeTheorems.v

Add some theorems about context graphs and simplify some proofs about overtrees.
**Fixes:** N/A

Add some theorems about context graphs and simplify some proofs about overtrees

---

proofs/Experiments/ContextGraph/README.md
proofs/Experiments/Overtree/README.md

Update a couple READMEs.
**Fixes:** N/A

Update a couple READMEs

---

proofs/Experiments/ProxyGraph/TrivialProxyGraph.v

Fix a few typos in comments.
**Fixes:** N/A

Fix a few typos in comments

---

proofs/ContextGraph/ContextGraph.v
proofs/ContextGraph/README.md
proofs/ContextGraph/TrivialContextGraph.v

Wordsmith the context graph README.
**Fixes:** N/A

Wordsmith the context graph README

---

proofs/ContextGraph/ContextGraph.v
proofs/ContextGraph/README.md

Wordsmith the context graph development.
**Fixes:** N/A

Wordsmith the context graph development

---

proofs/ContextGraph/ContextGraphTheorems.v

Prove a couple of basic theorems about context graphs.
**Fixes:** N/A

Prove a couple of basic theorems about context graphs

---

proofs/ContextGraph/ContextGraph.v
proofs/ContextGraph/ContextGraphTheorems.v
proofs/ContextGraph/README.md
proofs/ContextGraph/TrivialContextGraph.v

Add an `abstraction` axiom to context graphs.
**Fixes:** N/A

Add an `abstraction` axiom to context graphs

---

proofs/ContextGraph/README.md

Simplify the description of context graphs.
**Fixes:** N/A

Simplify the description of context graphs

---

proofs/GranularityGraph/GranularityGraph.v
proofs/GranularityGraph/GranularityGraphTheorems.v
proofs/GranularityGraph/TrivialGranularityGraph.v

Rename some concepts related to granularity graphs.
**Fixes:** N/A

Rename some concepts related to granularity graphs

---

proofs/GranularityGraph/README.md

Wordsmith the granularity graph README.
**Fixes:** N/A

Wordsmith the granularity graph README

---

proofs/GranularityGraph/GranularityGraph.v
proofs/GranularityGraph/TrivialGranularityGraph.v

Wordsmith the granularity graph comments.
**Fixes:** N/A

Wordsmith the granularity graph comments

---

proofs/GranularityGraph/GranularityGraph.v
proofs/GranularityGraph/GranularityGraphTheorems.v
proofs/GranularityGraph/README.md
proofs/GranularityGraph/TrivialGranularityGraph.v

Fix (and rename) the `reflection` axiom.
**Fixes:** N/A

Fix (and rename) the `reflection` axiom

---

proofs/GranularityGraph/README.md

Add syntax highlighting for a code snippet.
**Fixes:** N/A

Add syntax highlighting for a code snippet

---

proofs/GranularityGraph/GranularityGraph.v
proofs/GranularityGraph/GranularityGraphTheorems.v
proofs/GranularityGraph/TrivialGranularityGraph.v

Update the `sharing` axiom and prove a theorem about it.
**Fixes:** N/A

Update the `sharing` axiom and prove a theorem about it

---

proofs/GranularityGraph/GranularityGraph.v
proofs/GranularityGraph/GranularityGraphTheorems.v
proofs/GranularityGraph/README.md
proofs/GranularityGraph/TrivialGranularityGraph.v

Update the `sharing` axiom.
**Fixes:** N/A

Update the `sharing` axiom

---

proofs/GranularityGraph/GranularityGraph.v
proofs/GranularityGraph/GranularityGraphTheorems.v

Remove the `sharing` axiom.
**Fixes:** N/A

Remove the `sharing` axiom

---

proofs/GranularityGraph/README.md
proofs/Overtree/Overtree.v
proofs/Overtree/OvertreeTheorems.v
proofs/Overtree/README.md
proofs/Overtree/TrivialOvertree.v

Bring back overtrees.
**Fixes:** N/A

Bring back overtrees

---

proofs/GranularityGraph/GranularityGraph.v
proofs/GranularityGraph/README.md
proofs/GranularityGraph/TrivialGranularityGraph.v

Refactor the granularity graph presentation.
**Fixes:** N/A

Refactor the granularity graph presentation

---

proofs/GranularityGraph/GranularityGraphTheorems.v
proofs/GranularityGraph/README.md

Add some theorems about granularity graphs.
**Fixes:** N/A

Add some theorems about granularity graphs

---

proofs/GranularityGraph/GranularityGraphTheorems.v

Rename some variables.
**Fixes:** N/A

Rename some variables

---

proofs/Graphs/BubbleGraph/BubbleGraph.v
proofs/Graphs/BubbleGraph/BubbleGraphTheorems.v
proofs/Graphs/BubbleGraph/README.md
proofs/Graphs/BubbleGraph/TrivialBubbleGraph.v
proofs/Graphs/GranularityGraph/GranularityGraphTheorems.v
proofs/Graphs/Overtree/OvertreeTheorems.v

Introduce bubble graphs.
**Fixes:** N/A

Introduce bubble graphs

---

proofs/Graphs/BubbleGraph/BubbleGraph.v
proofs/Graphs/BubbleGraph/TrivialBubbleGraph.v

Remove unnecessary parentheses.
**Fixes:** N/A

Remove unnecessary parentheses

---

proofs/Graphs/BubbleGraph/BubbleGraphTheorems.v

Prove a theorem about bubble graphs.
**Fixes:** N/A

Prove a theorem about bubble graphs

---

proofs/Graphs/BubbleGraph/README.md

Reflow a paragraph.
**Fixes:** N/A

Reflow a paragraph

---

proofs/Graphs/BubbleGraph/TrivialBubbleGraph.v

Simplify the "trivial" bubble graph.
**Fixes:** N/A

Simplify the "trivial" bubble graph

---

proofs/Graphs/GranularityGraph/TrivialGranularityGraph.v

Simplify the "trivial" granularity graph.
**Fixes:** N/A

Simplify the "trivial" granularity graph

---

proofs/Graphs/Overtree/Overtree.v
proofs/Graphs/Overtree/OvertreeTheorems.v
proofs/Graphs/Overtree/README.md
proofs/Graphs/Overtree/TrivialOvertree.v

Simplify the overtree development.
**Fixes:** N/A

Simplify the overtree development

---

proofs/Graphs/Overtree/Overtree.v
proofs/Graphs/Overtree/TrivialOvertree.v

Rename an axiom for consistency.
**Fixes:** N/A

Rename an axiom for consistency

---

proofs/Graphs/Overdag/Overdag.v
proofs/Graphs/Overdag/OverdagTheorems.v
proofs/Graphs/Overdag/README.md
proofs/Graphs/Overdag/TrivialOverdag.v
proofs/Graphs/Overtree/OvertreeTheorems.v

Introduce overdags.
**Fixes:** N/A

Introduce overdags

---

proofs/Graphs/BubbleGraph/BubbleGraphTheorems.v
proofs/Graphs/Overdag/OverdagTheorems.v

Prove a couple more theorems about overdags.
**Fixes:** N/A

Prove a couple more theorems about overdags

---

proofs/Graphs/BubbleGraph/BubbleGraphTheorems.v
proofs/Graphs/Overdag/Overdag.v
proofs/Graphs/Overdag/OverdagTheorems.v
proofs/Graphs/Overdag/TrivialOverdag.v
proofs/Graphs/Overtree/Overtree.v
proofs/Graphs/Overtree/OvertreeTheorems.v

Prove a theorem about overtrees.
**Fixes:** N/A

Prove a theorem about overtrees

---

proofs/Graphs/CausalCoverGraph/CausalCoverGraph.v
proofs/Graphs/CausalCoverGraph/CausalCoverGraphTheorems.v
proofs/Graphs/CausalCoverGraph/README.md
proofs/Graphs/CausalCoverGraph/TrivialCausalCoverGraph.v

Introduce the notion of *causal cover graph*.
**Fixes:** N/A

Introduce the notion of *causal cover graph*

---

proofs/Graphs/CausalCoverGraph/CausalCoverGraphTheorems.v

Prove an interesting theorem about causal cover graphs.
**Fixes:** N/A

Prove an interesting theorem about causal cover graphs

---

proofs/Graphs/CausalCoverGraph/CausalCoverGraph.v

Wordsmith some exposition.
**Fixes:** N/A

Wordsmith some exposition

---

proofs/Graphs/Gigamesh/Gigamesh.v
proofs/Graphs/Gigamesh/GigameshTheorems.v
proofs/Graphs/Gigamesh/README.md
proofs/Graphs/Gigamesh/TrivialGigamesh.v

Introduce the notion of gigamesh.
**Fixes:** N/A

Introduce the notion of gigamesh

---

proofs/Graphs/Gigamesh/Gigamesh.v
proofs/Graphs/Gigamesh/GigameshTheorems.v
proofs/Graphs/Gigamesh/TrivialGigamesh.v

Remove the `convexity` axiom.
**Fixes:** N/A

Remove the `convexity` axiom

---

proofs/Graphs/Gigamesh/Gigamesh.v
proofs/Graphs/Gigamesh/GigameshTheorems.v
proofs/Graphs/Gigamesh/TrivialGigamesh.v

Add the `rootedness` axiom to the gigamesh formulation.
**Fixes:** N/A

Add the `rootedness` axiom to the gigamesh formulation

---

proofs/Graphs/Gigamesh/Gigamesh.v
proofs/Graphs/Gigamesh/TrivialGigamesh.v

Reorder some things in the gigamesh development.
**Fixes:** N/A

Reorder some things in the gigamesh development

---

proofs/Gigamesh/Gigamesh.v
proofs/Gigamesh/GigameshTheorems.v
proofs/Gigamesh/TrivialGigamesh.v

Tweak the `connectedness` axiom in the gigamesh development.
**Fixes:** N/A

Tweak the `connectedness` axiom in the gigamesh development

---

proofs/Gigamesh/Gigamesh.v
proofs/Gigamesh/TrivialGigamesh.v

Elaborate in some comments in the gigamesh development.
**Fixes:** N/A

Elaborate in some comments in the gigamesh development

---

proofs/Gigamesh/Gigamesh.v
proofs/Gigamesh/GigameshTheorems.v
proofs/Gigamesh/TrivialGigamesh.v

Allow gigamesh nodes to have multiple parents and reformulate the encapsulation axiom.
**Fixes:** N/A

Allow gigamesh nodes to have multiple parents and reformulate the encapsulation axiom

---

linters/lint-imports.rb
proofs/AdmissibilityGraph/AdmissibilityGraphTheorems.v
proofs/ICBICS/ICBICS.v
proofs/Tactics.v
toast.yml

Remove some unused imports.
**Fixes:** N/A

Remove some unused imports

---

proofs/AdmissibilityGraph/TrivialAdmissibilityGraph.v

Simplify the simplest admissibility graph.
**Fixes:** N/A

Simplify the simplest admissibility graph

---

proofs/AdmissibilityGraph/AdmissibilityGraph.v
proofs/AdmissibilityGraph/AdmissibilityGraphTheorems.v
proofs/AdmissibilityGraph/README.md
proofs/AdmissibilityGraph/TrivialAdmissibilityGraph.v

Flesh out the README for admissibility graphs.
**Fixes:** N/A

Flesh out the README for admissibility graphs

---

proofs/AdmissibilityGraph/AdmissibilityGraphTheorems.v
proofs/AdmissibilityGraph/README.md

Prove a few more theorems about admissibility graphs and update the README.
**Fixes:** N/A

Prove a few more theorems about admissibility graphs and update the README

---

proofs/AdmissibilityGraph/README.md

Wordsmith the admissibility graph README.
**Fixes:** N/A

Wordsmith the admissibility graph README

---

proofs/AdmissibilityGraph/AdmissibilityGraph.v
proofs/AdmissibilityGraph/AdmissibilityGraphTheorems.v
proofs/AdmissibilityGraph/README.md
proofs/AdmissibilityGraph/TrivialAdmissibilityGraph.v

Introduce a reflexivity axiom to the admissibility graph development.
**Fixes:** N/A

Introduce a reflexivity axiom to the admissibility graph development

---

proofs/AdmissibilityGraph/README.md

Add some common admissibility graph patterns.
**Fixes:** N/A

Add some common admissibility graph patterns

---

proofs/AdmissibilityGraph/README.md

Flesh out the admissibility graph patterns.
**Fixes:** N/A

Flesh out the admissibility graph patterns

---

proofs/AdmissibilityGraph/README.md

Replace the examples in the admissibility graph development.
**Fixes:** N/A

Replace the examples in the admissibility graph development

---

proofs/AdmissibilityGraph/Examples/Simple.v
proofs/AdmissibilityGraph/Examples/SingleModule.v
proofs/AdmissibilityGraph/Examples/Trivial.v
proofs/AdmissibilityGraph/README.md

Add another admissibility graph example.
**Fixes:** N/A

Add another admissibility graph example

---

proofs/AdmissibilityGraph/README.md

Fix a category error in the admissibility graph README.
**Fixes:** N/A

Fix a category error in the admissibility graph README

---

proofs/AdmissibilityGraph/README.md

Reword the definition of admissibility to make it less awkward.
**Fixes:** N/A

Reword the definition of admissibility to make it less awkward

---

proofs/AdmissibilityGraph/README.md

Simplify a diagram.
**Fixes:** N/A

Simplify a diagram

---

proofs/AdmissibilityGraph/AdmissibilityGraphTheorems.v

Rewrite some comments to be more precise.
**Fixes:** N/A

Rewrite some comments to be more precise

---

proofs/AdmissibilityGraph/Examples/Simple.v
proofs/AdmissibilityGraph/Examples/SingleModule.v

Refactor some proofs.
**Fixes:** N/A

Refactor some proofs

---

proofs/AdmissibilityGraph/AdmissibilityGraphTheorems.v

Prove an obvious theorem about admissibility graphs.
**Fixes:** N/A

Prove an obvious theorem about admissibility graphs

---

proofs/AdmissibilityGraph/README.md

Define an algorithm for verifying admissibility graphs.
**Fixes:** N/A

Define an algorithm for verifying admissibility graphs

---

proofs/AdmissibilityGraph/README.md

Wordsmith the admissibility graphs README.
**Fixes:** N/A

Wordsmith the admissibility graphs README

---

proofs/AdmissibilityGraph/README.md

Use 𝒪 for big oh notation.
**Fixes:** N/A

Use 𝒪 for big oh notation

---

proofs/AdmissibilityGraph/README.md

Fix a typo in the admissibility graphs README.
**Fixes:** N/A

Fix a typo in the admissibility graphs README

---

proofs/AdmissibilityGraph/README.md

Make the admissibility graph images smaller.
**Fixes:** N/A

Make the admissibility graph images smaller

---

proofs/AdmissibilityGraph/README.md

Remove dependencies from the definition of admissibility graph.
**Fixes:** N/A

Remove dependencies from the definition of admissibility graph

---

proofs/AdmissibilityGraph/AdmissibilityGraph.v
proofs/AdmissibilityGraph/Examples/Simple.v
proofs/AdmissibilityGraph/Examples/SingleModule.v
proofs/AdmissibilityGraph/Examples/Trivial.v

Update the admissibility graph development to match the exposition.
**Fixes:** N/A

Update the admissibility graph development to match the exposition

---

proofs/AdmissibilityGraph/README.md

Add a note about circular dependencies.
**Fixes:** N/A

Add a note about circular dependencies

---

proofs/AdmissibilityGraph/README.md

Remove a weird question from the admissibility graphs README.
**Fixes:** N/A

Remove a weird question from the admissibility graphs README

---

proofs/ProxyGraph/ProxyGraph.v
proofs/ProxyGraph/README.md

Formalize proxy graphs.
**Fixes:** N/A

Formalize proxy graphs

---

proofs/ProxyGraph/ProxyGraph.v

Reformat a theorem.
**Fixes:** N/A

Reformat a theorem

---

toast.yml

Update Coq to v8.16.1.
**Fixes:** N/A

Update Coq to v8.16.1

---

proofs/ProxyGraph/ProxyGraph.v
proofs/ProxyGraph/README.md

Do some wordsmithing on the proxy graph development.
**Fixes:** N/A

Do some wordsmithing on the proxy graph development

---

proofs/ProxyGraph/README.md

Explain the name "proxy graph".
**Fixes:** N/A

Explain the name "proxy graph"

---

proofs/ProxyGraph/ProxyGraph.v
proofs/ProxyGraph/README.md

Prove a theorem about proxy graphs.
**Fixes:** N/A

Prove a theorem about proxy graphs

---

proofs/ProxyGraph/README.md

Fix a typo in the proxy graphs exposition.
**Fixes:** N/A

Fix a typo in the proxy graphs exposition

---

proofs/ProxyGraph/ProxyGraph.v
proofs/ProxyGraph/README.md

Update the proxy graphs formulation such that nodes, rather than edges, propagate egress and ingress.
**Fixes:** N/A

Update the proxy graphs formulation such that nodes, rather than edges, propagate egress and ingress

---

proofs/ProxyGraph/README.md

Fix the ordering of items in a numbered list.
**Fixes:** N/A

Fix the ordering of items in a numbered list

---

proofs/ProxyGraph/ProxyGraph.v
proofs/ProxyGraph/README.md

Rename some things.
**Fixes:** N/A

Rename some things

---

proofs/ProxyGraph/README.md

Rephrase an axiom in the proxy graph development and fix some typos.
**Fixes:** N/A

Rephrase an axiom in the proxy graph development and fix some typos

---

proofs/ProxyGraph/ProxyGraph.v

Do some alpha-renaming to avoid name collisions.
**Fixes:** N/A

Do some alpha-renaming to avoid name collisions

---

proofs/ProxyGraph/ProxyGraph.v
proofs/ProxyGraph/README.md

Change the `allowed` relation in the proxy graph formulation.
**Fixes:** N/A

Change the `allowed` relation in the proxy graph formulation

---

proofs/ProxyGraph/README.md

Wordsmith the proxy graph exposition.
**Fixes:** N/A

Wordsmith the proxy graph exposition

---

proofs/AdmissibilityGraph/AdmissibilityGraph.v
proofs/AdmissibilityGraph/README.md

Update the admissibility graphs development.
**Fixes:** N/A

Update the admissibility graphs development

---

proofs/TypeTheory/Reflection.v

Bring back the proof-by-reflection development.
**Fixes:** N/A

Bring back the proof-by-reflection development

---

toast.yml

Update Coq to v8.17.1.
**Fixes:** N/A

Update Coq to v8.17.1

---

proofs/CategoryTheory/Arrow.v
proofs/CategoryTheory/Category.v
proofs/CategoryTheory/Coproduct.v
proofs/CategoryTheory/Equivalence.v
proofs/CategoryTheory/Examples/Cat.v
proofs/CategoryTheory/Examples/Maybe.v
proofs/CategoryTheory/Examples/Set.v
proofs/CategoryTheory/Functor.v
proofs/CategoryTheory/Monad.v
proofs/CategoryTheory/NaturalTransformation.v
proofs/CategoryTheory/Object.v
proofs/CategoryTheory/Product.v
proofs/CategoryTheory/ProductCategory.v
proofs/CategoryTheory/Terminal.v
proofs/Tactics.v
proofs/Tutorial/Lesson2_DependentTypes.v
proofs/Tutorial/Lesson3_Logic.v

Update the category theory development.
**Fixes:** N/A

Update the category theory development

---

proofs/CategoryTheory/Category.v
proofs/ICBICS/ICBICS.v
proofs/SystemF/LocalClosure.v
proofs/SystemF/Opening.v
proofs/Tactics.v

Make the definition of category more modular.
**Fixes:** N/A

Make the definition of category more modular

---

proofs/TypeTheory/MutualInduction.v

Demonstrate that mutual induction can be emulated with an index.
**Fixes:** N/A

Demonstrate that mutual induction can be emulated with an index

---

proofs/CRDT/CRDT.v
proofs/CRDT/README.md

Formalize state-based CRDTs and prove the strong convergence theorem.
**Fixes:** N/A

Formalize state-based CRDTs and prove the strong convergence theorem

---

proofs/CRDT/CRDT.v

Make the CRDT formulation more closely resemble the literature.
**Fixes:** N/A

Make the CRDT formulation more closely resemble the literature

---

proofs/CRDT/CRDT.v

Add an example of a simple CRDT and prove that it is a CRDT.
**Fixes:** N/A

Add an example of a simple CRDT and prove that it is a CRDT

---

proofs/CRDT/CRDT.v

Make a comment read more naturally.
**Fixes:** N/A

Make a comment read more naturally

---

proofs/CRDT/CRDT.v

Refactor the CRDT formalization.
**Fixes:** N/A

Refactor the CRDT formalization

---

proofs/CRDT/StateCRDT.v

Rename a variable for consistency.
**Fixes:** N/A

Rename a variable for consistency

---

proofs/CRDT/StateCRDT.v

Reorder some adjectives.
**Fixes:** N/A

Reorder some adjectives

---

proofs/CRDT/StateCRDT.v

Refactor the formulation of state-based CRDTs.
**Fixes:** N/A

Refactor the formulation of state-based CRDTs

---

proofs/CRDT/OperationCRDT.v

Formalize operation-based CRDTs.
**Fixes:** N/A

Formalize operation-based CRDTs

---

proofs/CRDT/OperationCRDT.v

Rename some things in the formalization of operation-based CRDTs.
**Fixes:** N/A

Rename some things in the formalization of operation-based CRDTs

---

proofs/CRDT/OperationCRDT.v

Refactor the formulation of operation-based CRDTs.
**Fixes:** N/A

Refactor the formulation of operation-based CRDTs

---

proofs/CRDT/OperationCRDT.v

Rename a theorem.
**Fixes:** N/A

Rename a theorem

---

proofs/CRDT/OperationCRDT.v
proofs/CRDT/StateCRDT.v

Weaken the commutativity requirement for operation-based CRDTs.
**Fixes:** N/A

Weaken the commutativity requirement for operation-based CRDTs

---

proofs/CRDT/OperationCRDT.v

Rewrite some comments for clarity.
**Fixes:** N/A

Rewrite some comments for clarity

---

proofs/Tutorial/Lesson6_Extraction.v
toast.yml

Update the import linting configuration.
**Fixes:** N/A

Update the import linting configuration

---

proofs/crdt/operation_crdt.v
proofs/crdt/state_crdt.v

Fix the case of some identifiers in the CRDT development.
**Fixes:** N/A

Fix the case of some identifiers in the CRDT development

---

README.md
proofs/crdt/README.md

Wordsmith a couple of READMEs.
**Fixes:** N/A

Wordsmith a couple of READMEs

---

proofs/crdt/state_crdt.v

Fix the capitalization of a word in some comments.
**Fixes:** N/A

Fix the capitalization of a word in some comments

---

proofs/tutorial/lesson1_functional_programming.v

Fix a couple of typos in the tutorial.
**Fixes:** N/A

Fix a couple of typos in the tutorial

---

proofs/admissibility_graph/README.md

Make a sentence more clear in the admissibility graphs README.
**Fixes:** N/A

Make a sentence more clear in the admissibility graphs README

---

proofs/admissibility_graph/README.md
proofs/admissibility_graph/admissibility_graph.v

Fix the statement of the admissibility reflection theorem.
**Fixes:** N/A

Fix the statement of the admissibility reflection theorem

---

proofs/admissibility_graph/README.md
proofs/admissibility_graph/admissibility_graph.v

Formalize the concept of a wooden admissibility graph.
**Fixes:** N/A

Formalize the concept of a wooden admissibility graph

---

proofs/admissibility_graph/README.md
proofs/admissibility_graph/admissibility_graph.v

Generalize the encapsulation and sandboxing theorems in the admissibility graphs development.
**Fixes:** N/A

Generalize the encapsulation and sandboxing theorems in the admissibility graphs development

---

proofs/admissibility_graph/README.md
proofs/admissibility_graph/admissibility_graph.v

Reformulate encapsulation and sandboxing as direct consequences of more general theorems.
**Fixes:** N/A

Reformulate encapsulation and sandboxing as direct consequences of more general theorems

---

proofs/admissibility_graph/README.md
proofs/admissibility_graph/admissibility_graph.v

Generalize the encapsulation and sandboxing theorems.
**Fixes:** N/A

Generalize the encapsulation and sandboxing theorems

---

proofs/admissibility_graph/README.md
proofs/admissibility_graph/admissibility_graph.v

Define the transpose of an admissibility graph.
**Fixes:** N/A

Define the transpose of an admissibility graph

---

proofs/admissibility_graph/README.md
proofs/admissibility_graph/admissibility_graph.v

Formalize the concepts of `protects` and `contains`.
**Fixes:** N/A

Formalize the concepts of `protects` and `contains`

---

proofs/admissibility_graph/README.md
proofs/admissibility_graph/admissibility_graph.v

Refactor the admissibility graphs development.
**Fixes:** N/A

Refactor the admissibility graphs development

---

proofs/admissibility_graph/README.md
proofs/admissibility_graph/admissibility_graph.v

Formalize modularity.
**Fixes:** N/A

Formalize modularity

---

proofs/admissibility_graph/README.md

Fix some formatting in the admissibility graphs README.
**Fixes:** N/A

Fix some formatting in the admissibility graphs README

---

proofs/tactics.v
toast.yml

Update Coq to v8.18.0.
**Fixes:** N/A

Update Coq to v8.18.0

---

proofs/admissibility_graph/admissibility_graph.v

Prove some admissibility theorems.
**Fixes:** N/A

Prove some admissibility theorems

---

proofs/admissibility_graph/README.md
proofs/admissibility_graph/admissibility_graph.v

Prove some modularity theorems.
**Fixes:** N/A

Prove some modularity theorems

---

proofs/admissibility_graph/README.md

Add some missing punctuation.
**Fixes:** N/A

Add some missing punctuation

---

proofs/admissibility_graph/README.md
proofs/admissibility_graph/admissibility_graph.v

Reformulate modularity.
**Fixes:** N/A

Reformulate modularity

---

proofs/admissibility_graph/README.md
proofs/admissibility_graph/admissibility_graph.v

Formulate and prove the modularity theorem.
**Fixes:** N/A

Formulate and prove the modularity theorem

---

proofs/admissibility_graph/README.md
proofs/admissibility_graph/admissibility_graph.v

Reorder a few theorems.
**Fixes:** N/A

Reorder a few theorems

---

proofs/admissibility_graph/README.md
proofs/admissibility_graph/admissibility_graph.v

Remove a useless theorem.
**Fixes:** N/A

Remove a useless theorem

---

proofs/admissibility_graph/admissibility_graph.v

Prove some lemmas about admissibility graphs.
**Fixes:** N/A

Prove some lemmas about admissibility graphs

---

proofs/admissibility_graph/admissibility_graph.v

Fix the case of an identifier.
**Fixes:** N/A

Fix the case of an identifier

---

proofs/admissibility_graph/README.md
proofs/admissibility_graph/admissibility_graph.v

Define encapsulation and sandboxing.
**Fixes:** N/A

Define encapsulation and sandboxing

---

proofs/admissibility_graph/README.md
proofs/admissibility_graph/admissibility_graph.v

Explain the intuitive motivation for encapsulation and sandboxing.
**Fixes:** N/A

Explain the intuitive motivation for encapsulation and sandboxing

---

toast.yml

Use `set -x` for shell scripts.
**Fixes:** N/A

Use `set -x` for shell scripts

---

toast.yml

Update the opam check to address a warning in the logs.
**Fixes:** N/A

Update the opam check to address a warning in the logs

---

proofs/type_theory/eta_equivalence.v

Add a discussion about eta equivalence.
**Fixes:** N/A

Add a discussion about eta equivalence

---

proofs/type_theory/eta_equivalence.v

Explain how eta contraction and cumulativity break subject reduction.
**Fixes:** N/A

Explain how eta contraction and cumulativity break subject reduction

---

proofs/type_theory/eta_equivalence.v

Clarify how eta contraction would break subject reduction in Coq.
**Fixes:** N/A

Clarify how eta contraction would break subject reduction in Coq

---

proofs/type_theory/eta_equivalence.v

Demonstrate eta conversion for records.
**Fixes:** N/A

Demonstrate eta conversion for records

---

proofs/system_f/local_closure.v
proofs/system_f/opening.v

Make the proofs compatible with Coq 8.19.1.
**Fixes:** https://github.com/stepchowfun/proofs/issues/665

Make the proofs compatible with Coq 8.19.1

---

proofs/type_theory/eta_equivalence.v

Fix a comment in the eta equivalence development.
**Fixes:** N/A

Fix a comment in the eta equivalence development

---

proofs/admissibility_graph/README.md

Add some GitHub-flavored formatting to the admissibility graphs README.
**Fixes:** N/A

Add some GitHub-flavored formatting to the admissibility graphs README

---

proofs/type_theory/eta_equivalence.v

Clarify the issue with eta contraction.
**Fixes:** N/A

Clarify the issue with eta contraction

---

proofs/type_theory/eta_equivalence.v

Remove some unnecessary parentheses.
**Fixes:** N/A

Remove some unnecessary parentheses

---

proofs/type_theory/girard.v

Use a lowercase name for a thing that is not a type.
**Fixes:** N/A

Use a lowercase name for a thing that is not a type

---

README.md
proofs/stlc/README.md
proofs/tutorial/README.md
proofs/tutorial/lesson5_consistency.v

Add some file and directory references.
**Fixes:** N/A

Add some file and directory references

---

README.md
toast.yml

Update Coq to v8.19.2.
**Fixes:** N/A

Update Coq to v8.19.2

---

proofs/type_theory/homotopy_type_theory.v

Prove that equivalence is an equivalence relation.
**Fixes:** N/A

Prove that equivalence is an equivalence relation

---

proofs/type_theory/homotopy_type_theory.v

Refactor some things in the HoTT development.
**Fixes:** N/A

Refactor some things in the HoTT development

---

proofs/type_theory/homotopy_type_theory.v

Use a consistent case convention.
**Fixes:** N/A

Use a consistent case convention

---

proofs/tutorial/lesson5_consistency.v
proofs/type_theory/homotopy_type_theory.v

Add a couple of tiny proofs and update some identifiers to adhere to the naming convention.
**Fixes:** N/A

Add a couple of tiny proofs and update some identifiers to adhere to the naming convention

---

proofs/tutorial/lesson5_consistency.v

Refactor some code in the consistency lesson.
**Fixes:** N/A

Refactor some code in the consistency lesson

---

proofs/tutorial/lesson2_dependent_types.v

Explain the convoy pattern in the tutorial.
**Fixes:** N/A

Explain the convoy pattern in the tutorial

---

proofs/tutorial/lesson1_functional_programming.v
proofs/tutorial/lesson2_dependent_types.v

Rephrase some type signatures.
**Fixes:** N/A

Rephrase some type signatures

---

README.md
proofs/icbics/icbics.v
toast.yml

Use non-deprecated versions of list-related lemmas.
**Fixes:** N/A

Use non-deprecated versions of list-related lemmas

---

proofs/tutorial/lesson2_dependent_types.v

Do some wordsmithing in the tutorial.
**Fixes:** N/A

Do some wordsmithing in the tutorial

---

proofs/tutorial/lesson2_dependent_types.v

Let an obvious type be inferred.
**Fixes:** N/A

Let an obvious type be inferred

---

proofs/tutorial/lesson5_consistency.v

Reorder some examples.
**Fixes:** N/A

Reorder some examples

---

toast.yml

Lint the tag references in the toastfile.
**Fixes:** N/A

Lint the tag references in the toastfile

---

proofs/type_theory/w.v

Add an exploration of W-types.
**Fixes:** N/A

Add an exploration of W-types

---

proofs/type_theory/w.v

Explain the poor ergonomics of W-types.
**Fixes:** N/A

Explain the poor ergonomics of W-types

---

proofs/type_theory/eta_equivalence.v
proofs/type_theory/w_types.v

Wordsmith the exposition in the W-types development.
**Fixes:** N/A

Wordsmith the exposition in the W-types development

---

proofs/type_theory/impredicative_encodings.v

Rename a file

---

proofs/type_theory/w_types.v

Add some underscores.
**Fixes:** N/A

Add some underscores

---

proofs/type_theory/w_types.v

Implement the W-encoded natural number type with a dependent eliminator.
**Fixes:** N/A

Implement the W-encoded natural number type with a dependent eliminator

---

proofs/kleene/kleene_theorems.v

Capitalize "Kleene".
**Fixes:** N/A

Capitalize "Kleene"

---

proofs/icbics/icbics.v

Fix an import

---

proofs/tutorial/lesson4_proof_techniques.v
proofs/tutorial/lesson6_extraction.v

Explain well-founded recursion.
**Fixes:** N/A

Explain well-founded recursion

---

proofs/tutorial/lesson4_proof_techniques.v

Tweak a proof

---

README.md

Update the instructions in the README.
**Fixes:** N/A

Update the instructions in the README

---

proofs/type_theory/well_founded.v

Wordsmith the well-foundedness development.
**Fixes:** N/A

Wordsmith the well-foundedness development

---

proofs/type_theory/well_founded.v

Reformat a definition.
**Fixes:** N/A

Reformat a definition

---

proofs/category_theory/category.v
proofs/category_theory/examples/cat.v
proofs/category_theory/examples/maybe.v
proofs/category_theory/examples/set.v
proofs/category_theory/functor.v
proofs/category_theory/natural_transformation.v
proofs/category_theory/product_category.v
proofs/crdt/operation_crdt.v
proofs/crdt/state_crdt.v
proofs/tutorial/lesson6_extraction.v
proofs/type_theory/well_founded.v

Stop using deprecated syntax.
**Fixes:** N/A

Stop using deprecated syntax

---

proofs/type_theory/homotopy_type_theory.v

Define homotopy n-types and prove a basic fact about them.
**Fixes:** N/A

Define homotopy n-types

---

proofs/type_theory/homotopy_type_theory.v

Simplify some things in the HoTT development.
**Fixes:** N/A

Simplify some things in the HoTT development

---

proofs/type_theory/homotopy_type_theory.v

Clarify some universes in the HoTT development.
**Fixes:** N/A

Clarify some universes in the HoTT development

---

proofs/type_theory/reflection.v

Update the proof by reflection development.
**Fixes:** N/A

Update the proof by reflection development

---

proofs/type_theory/homotopy_type_theory.v

Reformulate equivalence in the HoTT development.
**Fixes:** N/A

Reformulate equivalence in the HoTT development

---

proofs/type_theory/homotopy_type_theory.v

Prove that the fibers of a half-adjoint equivalence are contractible.
**Fixes:** N/A

Prove that the fibers of a half-adjoint equivalence are contractible

---

proofs/type_theory/homotopy_type_theory.v

Characterize the paths between homotopy fibers.
**Fixes:** N/A

Characterize the paths between homotopy fibers

---

proofs/type_theory/homotopy_type_theory.v

Reformulate one-sided inverses in the HoTT development.
**Fixes:** N/A

Reformulate one-sided inverses in the HoTT development

---

proofs/type_theory/homotopy_type_theory.v

Prove the propositional computation rule for univalence without tactics.
**Fixes:** N/A

Prove the propositional computation rule for univalence without tactics

---

proofs/type_theory/homotopy_type_theory.v

Prove the uniqueness principle for univalence.
**Fixes:** N/A

Prove the uniqueness principle for univalence

---

proofs/type_theory/homotopy_type_theory.v

Prove the propositional computation and uniqueness rules for paths between sigmas.
**Fixes:** N/A

Prove the propositional computation and uniqueness rules for paths between sigmas

---

proofs/type_theory/homotopy_type_theory.v

Introduce `equiv_to_path` and `homotopy_to_path`.
**Fixes:** N/A

Introduce `equiv_to_path` and `homotopy_to_path`

---

proofs/type_theory/homotopy_type_theory.v

Redefine `sigma_path_compute` and `sigma_path_unique` without proof mode.
**Fixes:** N/A

Redefine `sigma_path_compute` and `sigma_path_unique` without proof mode

---

proofs/type_theory/homotopy_type_theory.v

Prove some results about homotopy fibers.
**Fixes:** N/A

Prove some results about homotopy fibers

---

proofs/type_theory/homotopy_type_theory.v

Finish characterizing the path space of homotopy fibers.
**Fixes:** N/A

Finish characterizing the path space of homotopy fibers

---

proofs/type_theory/homotopy_type_theory.v

Prove that a couple of eliminators are equivalences.
**Fixes:** N/A

Prove that a couple of eliminators are equivalences
