stepchowfun/proofs

- Makefile
Sort targets in the Makefile and make the 'clean' target more robust.
> Sort targets in the Makefile and make the 'clean' target more robust

- coq/CategoryTheory/Category.v
- coq/Kleene.v
Use universe polymorphism so we can construct a category of categories. Also, remove some redundant tactics.
> Use universe polymorphism so we can construct a category of categories

- coq/CategoryTheory/NaturalTransformation.v
Add a comma between the metavariables for natural transformations.
> Add a comma between the metavariables for natural transformations

- Makefile
Update the Makefile to clean up temporary files even when the build fails.
> Update the Makefile to clean up temporary files even when the build fails

- coq/CategoryTheory/Cat.v
Remove the functional extensionality axiom from the `Cat` proof, since it's not used.
> Remove the functional extensionality axiom from the Cat proof, since it's not used

- .travis.yml
- coq/Intro.v
- coq/Kleene.v
- coq/Reflection.v
- coq/Stlc/Preservation.v
- coq/Stlc/Progress.v
- coq/Stlc/Soundness.v
- coq/Tactics.v
Switch from `eauto` to `auto` in the `magic` tactic to make the proofs less magical.
> Switch from eauto to auto

- coq/STLC/FreeVars.v
- coq/STLC/Preservation.v
Don't use `\/` or `/\` in inductive propositions, since that prevents Coq from generating good induction hypotheses.
After eliminating these from the `fIf` case by splitting it into three separate cases, I was able to delete part of a proof since Coq is now able to automate that part.
> Don't use \/ or /\ in inductive propositions

- coq/Kleene.v
- coq/STLC/Preservation.v
- coq/STLC/Progress.v
- coq/STLC/Soundness.v
- coq/Tactics.v
Don't use `eauto` in `magic`. It's too slow.
> Don't use eauto in magic

- coq/Tactics.v
Update the `gen` tactic to generalize in reverse order. That way the resulting goal will have the premises in the intended order.
> Update the 'gen' tactic to generalize in reverse order

- coq/STLC/FreeVar.v
- coq/STLC/Name.v
- coq/STLC/Preservation.v
- coq/STLC/Substitution.v
- coq/STLC/Syntax.v
- coq/STLC/Typing.v
Export the `Name` module so we don't have to import it everywhere.
> Export the 'Name' module

- coq/CategoryTheory/Cat.v
- coq/CategoryTheory/Maybe.v
Use shorter names for modules in the prelude.
> Use shorter names for modules in the prelude

- Makefile
Fail if `Admitted` is found in proofs.
> Fail if 'Admitted' is found in proofs

- Makefile
Make minor improvements to the `Makefile`:
- Do the `Admitted` check after the rest of linting so `make lint` is not useless when working on a partially-proven theorem.
- Collapse the `make` invocations in the `docker-build` target.
> Make minor improvements to the Makefile

- coq/Intro.v
- coq/Reflection.v
- coq/STLC/Preservation.v
Use `Theorem` instead of `Lemma` everywhere. That way I don't have to think about which one to use.
> Use 'Theorem' instead of 'Lemma' everywhere

- coq/STLC/Preservation.v
- coq/STLC/Typing.v
Rename `lookupVar` to `lookup` in the STLC presentation (to more closely match the System F version) and convert an `eapply` into `apply`.
> Rename lookupVar to lookup in the STLC presentation and convert an eapply into apply

- Makefile
Update the Makefile for Coq 8.8.0. It appears Coq renamed one of the intermediate files.
> Update the Makefile for Coq 8.8.0

- Makefile
Use `rm -f` to make the Makefile more robust.
> Use 'rm -f' to make the Makefile more robust

- coq/SystemF/Name.v
Make the proof of `nameFresh` a little more straightforward.
> Make the proof of nameFresh a little more straightforward

- coq/CategoryTheory/Category.v
Prove that the dual category construction is an involution. The proof depends on [proof irrelevance](https://coq.inria.fr/library/Coq.Logic.ProofIrrelevance.html), which is not implied by the metatheory of Coq.
> Prove that the dual category construction is an involution

- coq/CategoryTheory/Coproduct.v
Formalize coproducts, the categorical dual of products. This relationship with products is proven.
> Formalize coproducts

- coq/CategoryTheory/Category.v
- coq/CategoryTheory/Examples/Cat.v
Use proof irrelevance for the whole category theory development.
> Use proof irrelevance for the whole category theory development

- coq/CategoryTheory/Category.v
- coq/CategoryTheory/Examples/Cat.v
Certain results depend on axioms such as proof irrelevance or functional extensionality. We use these axioms where necessary, but we should not add them as hints to the global hints database (so it is clear which results depend on which axioms). This PR uses Coq's "section" mechanism to add such hints locally, such that the hint is no longer available when the section is closed.
> Don't add axioms to the global hints database

- coq/CategoryTheory/Arrow.v
- coq/CategoryTheory/Coproduct.v
- coq/CategoryTheory/Object.v
Prove that coproducts are unique up to isomorphism. The proof is by duality, using the already-proven result that products are unique up to isomorphism.
> Prove that coproducts are unique up to isomorphism

- coq/CategoryTheory/Monad.v
- coq/CategoryTheory/NaturalTransformation.v
Reorder the arguments of leftWhisker to make it more intuitive.
> Reorder the arguments of leftWhisker to make it more intuitive

- coq/CategoryTheory/Arrow.v
- coq/CategoryTheory/Category.v
- coq/CategoryTheory/Coproduct.v
- coq/CategoryTheory/Examples/Cat.v
- coq/CategoryTheory/Examples/Maybe.v
- coq/CategoryTheory/Examples/Set.v
- coq/CategoryTheory/Functor.v
- coq/CategoryTheory/NaturalTransformation.v
- coq/CategoryTheory/Object.v
- coq/CategoryTheory/Product.v
- coq/CategoryTheory/ProductCategory.v
Refactor some of the category theory development. In particular:
- For theorems whose type begin with `forall`, I just made the quantified variables parameters of the theorem. This is equivalent and shorter.
- I made invocations of `proof_irrelevance`, `functional_extensionality`, `functional_extensionality_dep` always explicit. Previously they were sometimes added as hints (within a section).
- I made all theorems opaque, such that only the computational contents of categories, functors, etc. are transparent. This makes proof terms smaller and easier to work with.
> Refactor some of the category theory development

- coq/Intro/Lesson3_Induction.v
Use `cbn` instead of `simpl`. The [documentation](https://coq.inria.fr/refman/proof-engine/tactics.html#coq:tacn.simpl) says:
> The `cbn` tactic is claimed to be a more principled, faster and more predictable replacement for `simpl`.
> Use `cbn` instead of `simpl`

- coq/CategoryTheory/Examples/Maybe.v
- coq/CategoryTheory/Examples/Set.v
- coq/Intro/Lesson0_Intro.v
- coq/Intro/Lesson1_DependentTypes.v
- coq/Intro/Lesson2_Logic.v
- coq/Kleene.v
- coq/Metatheory.v
- coq/STLC/Name.v
- coq/STLC/Syntax.v
- coq/SystemF/Name.v
- coq/SystemF/Syntax.v
Use `Type` instead of `Set` where a universe is required, otherwise just leave it out (Coq seems to default to `Type` already).
> Use `Type` instead of `Set`

- coq/CategoryTheory/Coproduct.v
- coq/CategoryTheory/Product.v
Prove categorically that `1 * X = X` and `X = 0 + X` (up to isomorphism), where `1` is a terminal object and `0` is an initial object.
> Prove categorically that 1 * X = X and X = 0 + X

- coq/CategoryTheory/Equivalence.v
Simplify the proof that equivalence of categories is reflexive.
> Simplify the proof that equivalence of categories is reflexive

- Makefile
- README.md
- scripts/lint-general.rb
- toast.yml
Bring back the Makefile (removed in https://github.com/stepchowfun/proofs/pull/182) for working with CoqIDE. After this change, [Toast](https://github.com/stepchowfun/toast) is only used for CI but not for local development. It would be nice to use Toast for local development as well, but apparently Coq modules that are compiled in Linux (via Docker) can't be used on macOS by CoqIDE. So we need a way to compile Coq code on the host.
> Bring back the Makefile for working with CoqIDE

- .github/workflows/ci.yml
- README.md
Switch from Travis to GitHub Actions for CI.
> Switch from Travis to GitHub Actions for CI

- Makefile
- _CoqProject
Require imports to have absolute names.
> Require imports to have absolute names

- proofs/ContextGraph/ContextGraph.v
Rename the two reachability relations for context graphs.
**Fixes:** N/A
> Rename the two reachability relations for context graphs

- proofs/ContextGraph/ContextGraph.v
- proofs/ContextGraph/TrivialContextGraph.v
Remove superfluous definitions from the context graph development.
**Fixes:** N/A
> Remove superfluous definitions from the context graph development

- proofs/Tutorial/Lesson5_Totality.v
Show that recursive occurrences of inductive types must be strictly positive, not just positive.
**Fixes:** N/A
> Show that recursive occurrences of inductive types must be strictly positive, not just positive

- proofs/CategoryTheory/Category.v
- proofs/CategoryTheory/Coproduct.v
- proofs/CategoryTheory/Examples/Maybe.v
- proofs/CategoryTheory/Functor.v
- proofs/CategoryTheory/Monad.v
- proofs/CategoryTheory/NaturalTransformation.v
- proofs/CategoryTheory/Object.v
- proofs/CategoryTheory/Product.v
- proofs/Kleene/KleeneData.v
- proofs/Kleene/KleeneTheorems.v
- proofs/SystemF/LocalClosure.v
- proofs/Tactics.v
- proofs/Tutorial/Lesson0_Intro.v
- proofs/Tutorial/Lesson1_DependentTypes.v
- proofs/Tutorial/Lesson2_Logic.v
- proofs/Tutorial/Lesson3_Induction.v
- proofs/Tutorial/Lesson4_Reflection.v
- proofs/Tutorial/Lesson5_Totality.v
- proofs/TypeTheory/Church.v
- proofs/TypeTheory/Girard.v
Use backticks to delimit code-like text.
**Fixes:** N/A
> Use backticks to delimit code-like text

- proofs/Tutorial/Lesson0_Intro.v
Use `Set` instead of `Type` to simplify the exposition.
**Fixes:** N/A
> Use `Set` instead of `Type` to simplify the exposition

- proofs/Tutorial/Lesson3_Logic.v
Use `intros` instead of `intro` in the tutorial for pedagogical simplicity.
**Fixes:** N/A
> Use `intros` instead of `intro` in the tutorial for pedagogical simplicity

- proofs/Gigamesh/Gigamesh.v
- proofs/Gigamesh/TrivialGigamesh.v
Require parenthood to be reflexive in the gigamesh development.
**Fixes:** N/A
> Require parenthood to be reflexive in the gigamesh development

- proofs/Gigamesh/Gigamesh.v
- proofs/Gigamesh/GigameshTheorems.v
- proofs/Gigamesh/TrivialGigamesh.v
In order to support call-by-need evaluation, restrict gigameshes such that each node has exactly one parent.
**Fixes:** N/A
> In order to support call-by-need evaluation, restrict gigameshes such that each node has exactly one parent

- proofs/AdmissibilityGraph/AdmissibilityGraph.v
- proofs/AdmissibilityGraph/README.md
- proofs/AdmissibilityGraph/TrivialAdmissibilityGraph.v
Remove the antisymmetry axiom from the admissibility graph development.
**Fixes:** N/A
> Remove the antisymmetry axiom from the admissibility graph development

- proofs/AdmissibilityGraph/AdmissibilityGraph.v
- proofs/AdmissibilityGraph/AdmissibilityGraphTheorems.v
- proofs/AdmissibilityGraph/Examples/Simple.v
- proofs/AdmissibilityGraph/Examples/SingleModule.v
- proofs/AdmissibilityGraph/Examples/Trivial.v
- proofs/AdmissibilityGraph/README.md
Flip the direction of the parent-child edges in the admissibility graph development.
**Fixes:** N/A
> Flip the direction of the parent-child edges in the admissibility graph development

- proofs/AdmissibilityGraph/README.md
- proofs/ProxyGraph/ProxyGraph.v
- proofs/ProxyGraph/README.md
Use the word "allowed" instead of "admitted" in the proxy graphs development.
**Fixes:** N/A
> Use the word "allowed" instead of "admitted" in the proxy graphs development

- proofs/AdmissibilityGraph/README.md
Make a note that admissibility graphs are a special case of proxy graphs.
**Fixes:** N/A
> Make a note that admissibility graphs are a special case of proxy graphs

- proofs/CategoryTheory/Equivalence.v
- proofs/CategoryTheory/Examples/Set.v
Use type inference to simplify a definition.
**Fixes:** N/A
> Use type inference to simplify a definition

- proofs/AdmissibilityGraph/AdmissibilityGraph.v
- proofs/CategoryTheory/Arrow.v
- proofs/CategoryTheory/Category.v
- proofs/CategoryTheory/Coproduct.v
- proofs/CategoryTheory/Examples/Cat.v
- proofs/CategoryTheory/Examples/Maybe.v
- proofs/CategoryTheory/Functor.v
- proofs/CategoryTheory/Initial.v
- proofs/CategoryTheory/Monad.v
- proofs/CategoryTheory/NaturalTransformation.v
- proofs/CategoryTheory/Object.v
- proofs/CategoryTheory/Product.v
- proofs/CategoryTheory/Terminal.v
- proofs/Tutorial/Lesson1_FunctionalProgramming.v
- proofs/Tutorial/Lesson2_DependentTypes.v
- proofs/Tutorial/Lesson3_Logic.v
- proofs/TypeTheory/Univalence.v
Use `[` and `]` instead of `{` and `}` for implicit arguments.
**Fixes:** N/A
> Use `[` and `]` instead of `{` and `}` for implicit arguments

- toast.yml
Install `pkg-config`, which is apparently needed to install Coq now.
**Fixes:** N/A
> Install `pkg-config`, which is apparently needed to install Coq now

- proofs/type_theory/homotopy_type_theory.v
Use Coq's `eq` instead of a custom identity type in the HoTT development.
**Fixes:** N/A
> Use Coq's `eq` instead of a custom identity type in the HoTT development

- proofs/type_theory/homotopy_type_theory.v
Use univalence to transport a proof.
**Fixes:** N/A
> Use univalence to transport a proof

- proofs/type_theory/homotopy_type_theory.v
Prove that equivalence is logically equivalent to quasi-inverse.
**Fixes:** N/A
> Prove that equivalence is logically equivalent to quasi-inverse

- proofs/type_theory/homotopy_type_theory.v
Reformulate `path_to_equivalence` in terms of `transport`.
**Fixes:** N/A
> Reformulate `path_to_equivalence` in terms of `transport`

- proofs/type_theory/w.v
Add an example of using the `Nat` eliminator in the W-types development.
**Fixes:** N/A
> Add an example of using the `Nat` eliminator in the W-types development

- proofs/type_theory/w_types.v
Fix the casing of an identifier.
**Fixes:** N/A
> Fix the casing of an identifier

- proofs/type_theory/w_types.v
Prove that 0 != 1 with the W-encoded natural number types.
**Fixes:** N/A
> Prove that 0 != 1 with the W-encoded natural number types

- proofs/tutorial/lesson4_proof_techniques.v
Make the proof of `compare_lengths_well_founded` more standard.
**Fixes:** N/A
> Make the proof of `compare_lengths_well_founded` more standard

- proofs/type_theory/well_founded.v
Wordsmith a comment in the well-founded recursion/induction development.
**Fixes:** N/A
> Wordsmith a comment in the well-founded recursion/induction development

- proofs/type_theory/homotopy_type_theory.v
Prove that left and right inverses of equivalences are contractible.
**Fixes:** N/A
> Prove that left and right inverses of equivalences are contractible
